### ISSUE TITLE
Running from a colab

### ISSUE THREAD

**Issue by steinhaug** [LajaSoft/cog-facebook-musicgen#1]
Hello, I am looking around for alterations of this MusicGen AI and found you. However I cannot get your code to run from my Colab, do you know how i could change the code ? 

The default goes like

    !python3 -m pip install -U git+https://github.com/facebookresearch/audiocraft#egg=audiocraft
    from audiocraft.models import musicgen
    from audiocraft.utils.notebook import display_audio
    import torch

then a example:

    model = musicgen.MusicGen.get_pretrained('medium', device='cuda')
    model.set_generation_params(duration=8)
    res = model.generate([
        '120bpm. A force of an electro beat that keeps on comming, a powerfull beat drummin from electrical beats below in a wild and surrealistic manner... spinning drops of electrical baselines in waves of electrical baselines. 144bpm', 
        'A force of an electro beat that keeps on comming, a powerfull beat drummin from electrical beats below in a wild and surrealistic manner... spinning drops of electrical baselines in waves of electrical baselines.',
        'Underground electro beats, rave party styled baselines exploding through the walls, wilder and wilder, baselines keeps spinning louder and louder, higher and higher....',
        'Incomming transmission with a steady drum and bass waveform, slowly growing slowly getting higher, steady as a train picking up steam... drum and bass heads....',
        'Metronome 50, total silence. Then the universe delivers the largest horn sound ripping through the air. Rubber band, tighten up and releast metronome 180 bongo beat from the jungle. Metronome 200 180 200 again 180. Rubber band tightened, rocket release metronome bass line 250. Jungle beats!',
        'a deep base, psy trance. Rnb  techno transmission, trance music becomming a sensual expression. Passionate, intimacate, deepacate romancanate almost deadly  acetate.... Rolling rainbows, doubling rainbows, flying stgars with unicorns riding musical vcibrations.',
        'a deep base, goa 130bpm psychedelic trance comming after you. Waving hands, wawing heads, legs, arms and . Rnb  techno transmission, trance music becomming a sensual expression. Passionate, intimacate, deepacate romancanate almost deadly  acetate.... Rolling rainbows, doubling rainbows, flying stgars with unicorns riding musical vcibrations.'
    ], progress=True)
    display_audio(res, 32000)

I was hoping running your code like: python predict.py .... or so

Or do I need to check out replica for this to work? :D I am trying to expand my Colab notebook.

https://colab.research.google.com/github/steinhaug/stable-diffusion/blob/main/text2audio/MusicGenCollcetions.ipynb

**Comment by zba** [comment]
Idk about collab it made to run in docker, mostly local, cog have some docks how to run them in clouds, i not checked it, sorry.  Also i saw while read them, that they can run not only on replica. For me cog is just fast way to create something fun 😀
